require 'json'
require_relative '../slide_generator'

module Slides
  # public/js/engine-data.js: everything the browser engine (public/js/engine-core.js) needs,
  # read from the same sources the Ruby engine uses. Loaded with a plain <script> tag so the
  # editor works from GitHub Pages and from file:// alike. Regenerate with `rake slides:site`;
  # test/site_test.rb fails when it is stale.
  module SiteBundle
    PATH = File.join(SlideGenerator::ENGINE_ROOT, 'public', 'js', 'engine-data.js')

    def self.data
      catalog = SlideGenerator.template_catalog
      logo = SlideGenerator::BindingContext.new({}, 0, {})

      {
        canvas: catalog[:canvas],
        promptRules: catalog.dig(:authoring, :prompt_rules),
        stylesCss: File.read(SlideGenerator::STYLES_PATH),
        themeDefaults: SlideGenerator.theme_defaults,
        templates: SlideGenerator.template_specs.transform_values do |spec|
          spec.slice(:label, :description, :required_fields, :optional_fields, :field_aliases, :best_for, :constraints)
        end,
        brands: SlideGenerator.brand_names.to_h do |name|
          brand = SlideGenerator.load_brand(name)
          [name, {
            name: brand[:name],
            description: brand[:description],
            theme: brand[:theme],
            fonts: brand[:fonts],
            mark: brand[:mark],
            logo: brand[:logo_path] && logo.send(:logo_data_uri, brand[:logo_path])
          }.compact]
        end
      }
    end

    def self.source
      <<~JS
        // Generated by `rake slides:site` from templates/styles.css, templates/catalog.yml, and brands/.
        // Do not edit by hand.
        (function (root) {
          const data = #{JSON.pretty_generate(data)};
          if (typeof module !== 'undefined') module.exports = data;
          else root.SLIDES_ENGINE_DATA = data;
        })(typeof self !== 'undefined' ? self : this);
      JS
    end

    def self.write
      File.write(PATH, source)
      PATH
    end

    def self.current?
      File.exist?(PATH) && File.read(PATH) == source
    end
  end
end
